apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: alpine
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/developer-guy/desired-state-repository
